name: Feature Branch CI and PR

on:
  push:
    branches:
      - develop

permissions:
  security-events: write
  contents: write
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest pytest-cov bandit
            pip install -r requirements.txt
  
      - name: Run tests
        run: |
            python -m pytest test
  
      - name: Lint code
        run: |
              # stop the build if there are Python syntax errors or undefined names
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
      - name: Run bandit SAST
        run: |
            bandit -r . --skip B101,B104,B107
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'sarif'
            exit-code: '1'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  Docker:
    runs-on: ubuntu-latest
    needs: [Testing]
    permissions: 
        packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: hadolint
      uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
      with:
        dockerfile: Dockerfile
    - name: set lower case owner name
      id: github-user
      run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_OUTPUT}
      env:
            OWNER: '${{ github.repository_owner }}'

    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
    -
        name: Login to GitHub Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
            push: true
            context: .
            tags: ghcr.io/${{ env.OWNER_LC }}/hivebox:${{ github.sha }} 

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
          image-ref: 'ghcr.io/${{ env.OWNER_LC }}/hivebox:${{ github.sha }}'
          format: 'sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: 'results.sarif'
    - name: Upload results to GitHub
      run: |
        cat results.sarif 
    - name: Upload Trivy scan results to GitHub Security tab
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'results.sarif'